import exp from "constants";

interface Transaction {
  name: string;
  category: string;
  transaction_date: string;
  amount: number;
  icon: string;
}

// const data: Transaction[] = [
//   {
//     name: "Benjamin Wright",
//     category: "General",
//     transaction_date: "07 Oct 2024",
//     amount: "+$37.51",
//     icon: "🚕",
//   },
//   {
//     name: "Charlotte Young",
//     category: "Food",
//     transaction_date: "04 Feb 2024",
//     amount: "+$289.51",
//     icon: "🎮",
//   },
//   {
//     name: "Sophia Martinez",
//     category: "Entertainment",
//     transaction_date: "05 Nov 2024",
//     amount: "-$401.71",
//     icon: "💳",
//   },
//   {
//     name: "Henry Scott",
//     category: "Travel",
//     transaction_date: "14 Apr 2024",
//     amount: "+$193.74",
//     icon: "💳",
//   },
//   {
//     name: "Liam Johnson",
//     category: "Food",
//     transaction_date: "07 Dec 2024",
//     amount: "+$436.48",
//     icon: "✈️",
//   },
//   {
//     name: "Henry Scott",
//     category: "Food",
//     transaction_date: "06 Dec 2024",
//     amount: "+$251.75",
//     icon: "🍔",
//   },
//   {
//     name: "Lucas Harris",
//     category: "Food",
//     transaction_date: "04 Mar 2024",
//     amount: "+$432.73",
//     icon: "💡",
//   },
//   {
//     name: "Sophia Martinez",
//     category: "Entertainment",
//     transaction_date: "24 Aug 2024",
//     amount: "+$368.28",
//     icon: "🛍️",
//   },
//   {
//     name: "Mason Taylor",
//     category: "Entertainment",
//     transaction_date: "28 Apr 2024",
//     amount: "-$216.02",
//     icon: "✈️",
//   },
//   {
//     name: "Alexander Walker",
//     category: "General",
//     transaction_date: "10 Jan 2024",
//     amount: "-$307.00",
//     icon: "🚕",
//   },
//   {
//     name: "Mason Taylor",
//     category: "Travel",
//     transaction_date: "14 Aug 2024",
//     amount: "-$344.37",
//     icon: "✈️",
//   },
//   {
//     name: "Olivia Smith",
//     category: "General",
//     transaction_date: "06 Jul 2024",
//     amount: "+$148.24",
//     icon: "🎮",
//   },
//   {
//     name: "Evelyn Adams",
//     category: "General",
//     transaction_date: "09 Oct 2024",
//     amount: "-$443.00",
//     icon: "💡",
//   },
//   {
//     name: "Alexander Walker",
//     category: "Entertainment",
//     transaction_date: "29 Oct 2024",
//     amount: "+$17.94",
//     icon: "🍔",
//   },
//   {
//     name: "Isabella White",
//     category: "General",
//     transaction_date: "15 Jul 2024",
//     amount: "+$29.93",
//     icon: "✈️",
//   },
//   {
//     name: "James Allen",
//     category: "Shopping",
//     transaction_date: "02 Sep 2024",
//     amount: "+$35.15",
//     icon: "🛒",
//   },
//   {
//     name: "Amelia Hall",
//     category: "Travel",
//     transaction_date: "25 Sep 2024",
//     amount: "-$288.61",
//     icon: "🏥",
//   },
//   {
//     name: "Noah Brown",
//     category: "Travel",
//     transaction_date: "16 Sep 2024",
//     amount: "-$96.89",
//     icon: "🍔",
//   },
//   {
//     name: "Ava Thomas",
//     category: "General",
//     transaction_date: "14 Jun 2024",
//     amount: "+$57.27",
//     icon: "🛒",
//   },
//   {
//     name: "Liam Johnson",
//     category: "Travel",
//     transaction_date: "14 Sep 2024",
//     amount: "-$265.94",
//     icon: "📚",
//   },
//   {
//     name: "Isabella White",
//     category: "Food",
//     transaction_date: "29 Jun 2024",
//     amount: "+$393.49",
//     icon: "🎵",
//   },
//   {
//     name: "Alexander Walker",
//     category: "Food",
//     transaction_date: "09 Aug 2024",
//     amount: "+$411.98",
//     icon: "✈️",
//   },
//   {
//     name: "Ethan Garcia",
//     category: "Health",
//     transaction_date: "31 Jan 2024",
//     amount: "-$418.50",
//     icon: "🚕",
//   },
//   {
//     name: "Emma Richardson",
//     category: "General",
//     transaction_date: "29 Jun 2024",
//     amount: "+$177.69",
//     icon: "🛒",
//   },
//   {
//     name: "Isabella White",
//     category: "Food",
//     transaction_date: "18 Dec 2024",
//     amount: "-$375.31",
//     icon: "🛒",
//   },
//   {
//     name: "Alexander Walker",
//     category: "Food",
//     transaction_date: "07 Mar 2024",
//     amount: "-$86.40",
//     icon: "💳",
//   },
//   {
//     name: "Sophia Martinez",
//     category: "Shopping",
//     transaction_date: "26 Feb 2024",
//     amount: "-$239.53",
//     icon: "🚕",
//   },
//   {
//     name: "Liam Johnson",
//     category: "Shopping",
//     transaction_date: "18 May 2024",
//     amount: "-$285.86",
//     icon: "🚕",
//   },
//   {
//     name: "Noah Brown",
//     category: "Food",
//     transaction_date: "03 Jul 2024",
//     amount: "+$361.79",
//     icon: "🚕",
//   },
//   {
//     name: "Isabella White",
//     category: "Entertainment",
//     transaction_date: "24 Nov 2024",
//     amount: "-$76.88",
//     icon: "🎮",
//   },
//   {
//     name: "Ava Thomas",
//     category: "Shopping",
//     transaction_date: "01 Dec 2024",
//     amount: "-$189.73",
//     icon: "💡",
//   },
//   {
//     name: "Charlotte Young",
//     category: "Entertainment",
//     transaction_date: "20 May 2024",
//     amount: "-$14.64",
//     icon: "🛍️",
//   },
//   {
//     name: "Henry Scott",
//     category: "Shopping",
//     transaction_date: "24 Nov 2024",
//     amount: "+$442.11",
//     icon: "🍔",
//   },
//   {
//     name: "Elijah Lewis",
//     category: "Food",
//     transaction_date: "10 Apr 2024",
//     amount: "-$422.50",
//     icon: "🍔",
//   },
//   {
//     name: "Sophia Martinez",
//     category: "Entertainment",
//     transaction_date: "01 Jan 2024",
//     amount: "+$266.16",
//     icon: "🍔",
//   },
//   {
//     name: "Harper King",
//     category: "General",
//     transaction_date: "26 Jan 2024",
//     amount: "+$37.34",
//     icon: "🛍️",
//   },
//   {
//     name: "Harper King",
//     category: "Entertainment",
//     transaction_date: "25 Mar 2024",
//     amount: "-$407.55",
//     icon: "🍔",
//   },
//   {
//     name: "Mason Taylor",
//     category: "General",
//     transaction_date: "19 Jun 2024",
//     amount: "+$322.44",
//     icon: "🏥",
//   },
//   {
//     name: "Ava Thomas",
//     category: "Entertainment",
//     transaction_date: "09 Jan 2024",
//     amount: "-$453.34",
//     icon: "🎵",
//   },
//   {
//     name: "Henry Scott",
//     category: "Entertainment",
//     transaction_date: "13 Nov 2024",
//     amount: "-$126.78",
//     icon: "🛍️",
//   },
//   {
//     name: "Liam Johnson",
//     category: "General",
//     transaction_date: "09 Jul 2024",
//     amount: "-$42.10",
//     icon: "🚕",
//   },
//   {
//     name: "Charlotte Young",
//     category: "Health",
//     transaction_date: "07 Feb 2024",
//     amount: "-$145.68",
//     icon: "📚",
//   },
//   {
//     name: "Ethan Garcia",
//     category: "Food",
//     transaction_date: "18 Aug 2024",
//     amount: "-$326.86",
//     icon: "🏥",
//   },
//   {
//     name: "Lucas Harris",
//     category: "Entertainment",
//     transaction_date: "30 Apr 2024",
//     amount: "+$179.25",
//     icon: "🍔",
//   },
//   {
//     name: "Ava Thomas",
//     category: "Entertainment",
//     transaction_date: "08 Jul 2024",
//     amount: "-$323.39",
//     icon: "📚",
//   },
//   {
//     name: "Amelia Hall",
//     category: "Shopping",
//     transaction_date: "04 Feb 2024",
//     amount: "-$492.91",
//     icon: "🎟️",
//   },
//   {
//     name: "Evelyn Adams",
//     category: "Health",
//     transaction_date: "09 May 2024",
//     amount: "-$115.30",
//     icon: "🎟️",
//   },
//   {
//     name: "Olivia Smith",
//     category: "Shopping",
//     transaction_date: "31 Oct 2024",
//     amount: "-$406.78",
//     icon: "🎟️",
//   },
//   {
//     name: "Mia Clark",
//     category: "Health",
//     transaction_date: "09 Oct 2024",
//     amount: "+$278.28",
//     icon: "📚",
//   },
//   {
//     name: "Lucas Harris",
//     category: "Food",
//     transaction_date: "07 Mar 2024",
//     amount: "-$310.97",
//     icon: "✈️",
//   },
// ];

// export default data;
